version: "3.4"

services:

    database: 
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgresDB
        ports:
            - 5001:5432
        volumes: 
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: